language: python
python:
    - "2.7"
before_script:
  - wget "http://gyamp.com/hiroshi/google_appengine_zip" -nv
  - unzip -q google_appengine_zip
  - sudo ln -s `pwd`/google_appengine /usr/local/google_appengine
script: ant test
