language: python
python:
    - "2.7"
before_script:
  - wget "http://gyamp.com/hiroshi/google_appengine_zip" -nv
  - unzip -q google_appengine_zip
  - export PATH=$PATH:$PWD/google_appengine
script: ant test
sudo: false
