runtime: python312

handlers:
  - url: /favicon\.ico
    static_files: static/img/favicon.ico
    upload: static/img/favicon\.ico
    secure: always

  - url: /static
    static_dir: static
    secure: always

  - url: /.well-known
    static_dir: .well-known

  - url: /.*
    script: auto
    secure: always
